[build-system]
requires = ["setuptools>=65", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "DeepMIMO"
version = "4.0.0a4"
authors = [
    { name = "JoÃ£o Morais" },
    { name = "Umut Demirhan" },
    { name = "Ahmed Alkhateeb" },
]
description = "DeepMIMO dataset generator library"
license-files = ["LICENSE"]
readme = "README.md"
requires-python = ">=3.10"
keywords = ["MIMO", "ray tracing", "dataset", "DeepMIMO", "raytracing", "wireless"]
classifiers = [
    "Development Status :: 3 - Alpha",
    "Programming Language :: Python :: 3",
    "Operating System :: OS Independent",
]
dependencies = [
    "matplotlib>=3.8.2",
    "numpy>=1.19.5",
    "scipy>=1.6.2",
    "tqdm>=4.59.0",
]

[tool.setuptools.packages.find]
include = ["deepmimo*"]


[project.urls]
Homepage = "https://deepmimo.net/" 